<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call|fm-tx|fm-rx) #REQUIRED>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="-1"
               card_name="tegrart5671"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="ulp" val="0"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>

    <path>
      <ctl name="Left Spk Reg Addr" val="0x40"/>
      <ctl name="Left Spk Reg Value" val="0x5a6b"/>
      <ctl name="Left Spk Reg Addr" val="0x59"/>
      <ctl name="Left Spk Reg Value" val="0x05cf"/>
      <ctl name="Left Spk Reg Addr" val="0x40"/>
      <ctl name="Left Spk Reg Value" val="0x0000"/>

      <ctl name="Right Spk Reg Addr" val="0x40"/>
      <ctl name="Right Spk Reg Value" val="0x5a6b"/>
      <ctl name="Right Spk Reg Addr" val="0x59"/>
      <ctl name="Right Spk Reg Value" val="0x05cf"/>
      <ctl name="Right Spk Reg Addr" val="0x40"/>
      <ctl name="Right Spk Reg Value" val="0x0000"/>

      <ctl name="Left Spk Safeguard Threshold" val="3.53V"/>
      <ctl name="Right Spk Safeguard Threshold" val="3.53V"/>
      <ctl name="Left Spk Safeguard Bypass" val="0"/>
      <ctl name="Right Spk Safeguard Bypass" val="0"/>

      <ctl name="Left Spk Coil Value" val="1uH"/>
      <ctl name="Right Spk Coil Value" val="1uH"/>
      <ctl name="Left Spk Inductance" val="39uH"/>
      <ctl name="Right Spk Inductance" val="39uH"/>

      <ctl name="Left Spk Boot Patch" val="tfa9890_boot.patch"/>
      <ctl name="Right Spk Boot Patch" val="tfa9890_boot.patch"/>
      <ctl name="Left Spk ROM Patch" val="tfa9890_rom.patch"/>
      <ctl name="Right Spk ROM Patch" val="tfa9890_rom.patch"/>
      <ctl name="Left Spk Speaker File" val="tfa9890_left.speaker"/>
      <ctl name="Right Spk Speaker File" val="tfa9890_right.speaker"/>
      <ctl name="Left Spk Config File" val="tfa9890.config"/>
      <ctl name="Right Spk Config File" val="tfa9890.config"/>
    </path>

    <playback>
      <device name="speaker">
        <path name="on">
          <ctl name="RxDP Mux" val="IF1 DAC" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="RxDP SRC Switch" val="Divided by 3" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP DL Mux" val="DSP" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC L2 Mux" val="IF1 DAC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC L2 Mux" val="TxDC DAC" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC R2 Mux" val="IF1 DAC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DA MONOL ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DA MONOL ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DA MONOR ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC2 Playback Volume" val="175"/>
          <ctl name="Mono DAC MIXL DAC L2 Switch" val="1"/>
          <ctl name="Mono DAC MIXR DAC L2 Switch" val="0" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Mono DAC MIXR DAC L2 Switch" val="1" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Mono DAC MIXR DAC R2 Switch" val="1" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Mono DAC MIXR DAC R2 Switch" val="0" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Mono ADC L1 Mux" val="Mono DAC MIXL"/>
          <ctl name="Mono ADC R1 Mux" val="Mono DAC MIXR"/>
          <ctl name="AD MONOL ASRC Switch" val="clk_sysy_div_out"/>
          <ctl name="AD MONOR ASRC Switch" val="clk_sysy_div_out"/>
          <ctl name="Mono ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Mono ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="IF2 ADC Mux" val="IF_ADC2"/>

          <ctl name="Left Spk Output Voltage" val="8.5V"/>
          <ctl name="Left Spk Output Voltage" val="9.5V" tag="speaker-raw"/>
          <ctl name="Left Spk Output Voltage" val="9.5V" tag="speakerleft-raw"/>
          <ctl name="Left Spk Output Voltage" val="9.5V" tag="speakerright-raw"/>
          <ctl name="Right Spk Output Voltage" val="8.5V"/>
          <ctl name="Right Spk Output Voltage" val="9.5V" tag="speaker-raw"/>
          <ctl name="Right Spk Output Voltage" val="9.5V" tag="speakerleft-raw"/>
          <ctl name="Right Spk Output Voltage" val="9.5V" tag="speakerright-raw"/>

          <ctl name="Left Spk Max Coil Current" val="1.9A"/>
          <ctl name="Left Spk Max Coil Current" val="3.8A" tag="speaker-raw"/>
          <ctl name="Left Spk Max Coil Current" val="3.8A" tag="speakerleft-raw"/>
          <ctl name="Left Spk Max Coil Current" val="3.8A" tag="speakerright-raw"/>
          <ctl name="Right Spk Max Coil Current" val="1.9A"/>
          <ctl name="Right Spk Max Coil Current" val="3.8A" tag="speaker-raw"/>
          <ctl name="Right Spk Max Coil Current" val="3.8A" tag="speakerleft-raw"/>
          <ctl name="Right Spk Max Coil Current" val="3.8A" tag="speakerright-raw"/>

          <ctl name="Left Spk Resistance" val="Auto"/>
          <ctl name="Left Spk Resistance" val="8Omh" tag="speaker-raw"/>
          <ctl name="Left Spk Resistance" val="8Omh" tag="speakerleft-raw"/>
          <ctl name="Right Spk Resistance" val="Auto"/>
          <ctl name="Right Spk Resistance" val="8Omh" tag="speaker-raw"/>
          <ctl name="Right Spk Resistance" val="8Omh" tag="speakerright-raw"/>

          <ctl name="Left Spk Input Interface Mux" val="Input1"/>
          <ctl name="Right Spk Input Interface Mux" val="Input1"/>
          <ctl name="Left Spk Input Channel Mux" val="Left"/>
          <ctl name="Right Spk Input Channel Mux" val="Right"/>
          <ctl name="Left Spk Amplifier Channel Mux" val="DSP"/>
          <ctl name="Left Spk Amplifier Channel Mux" val="Left" tag="speaker-raw"/>
          <ctl name="Left Spk Amplifier Channel Mux" val="Left" tag="speakerleft-raw"/>
          <ctl name="Right Spk Amplifier Channel Mux" val="DSP"/>
          <ctl name="Right Spk Amplifier Channel Mux" val="Right" tag="speaker-raw"/>
          <ctl name="Right Spk Amplifier Channel Mux" val="Right" tag="speakerright-raw"/>
          <ctl name="Left Spk Output Channel Mux" val="Gain" val1="AEC"/>
          <ctl name="Right Spk Output Channel Mux" val="Current" val1="Gain"/>
          <ctl name="Left Spk Output Interface Mux" val="DSP"/>
          <ctl name="Right Spk Output Interface Mux" val="DSP"/>
          <ctl name="Left Spk Gain Channel Mux" val="Right"/>
          <ctl name="Right Spk Gain Channel Mux" val="Left"/>

          <ctl name="Left Spk Preset File" val="tfa9890_left_music.preset" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Left Spk Preset File" val="tfa9890_left_voice.preset" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Right Spk Preset File" val="tfa9890_right_music.preset" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Right Spk Preset File" val="tfa9890_right_voice.preset" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Left Spk Equalizer File" val="tfa9890_left_music.eq" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Left Spk Equalizer File" val="tfa9890_left_voice.eq" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Right Spk Equalizer File" val="tfa9890_right_music.eq" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="Right Spk Equalizer File" val="tfa9890_right_voice.eq" mode="AUDIO_MODE_IN_COMMUNICATION"/>

          <ctl name="Int Left Spk Switch" val="1"/>
          <ctl name="Int Left Spk Switch" val="0" tag="speakerright-raw"/>
          <ctl name="Int Right Spk Switch" val="1"/>
          <ctl name="Int Right Spk Switch" val="0" tag="speakerleft-raw"/>
        </path>
        <path name="off">
          <ctl name="Int Left Spk Switch" val="0"/>
          <ctl name="Int Right Spk Switch" val="0"/>
        </path>
      </device>
      <device name="headphone">
        <path name="on">
          <ctl name="RxDP Mux" val="IF1 DAC" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="RxDP SRC Switch" val="Divided by 3" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP DL Mux" val="DSP" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC L2 Mux" val="IF1 DAC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC L2 Mux" val="TxDC DAC" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC R2 Mux" val="IF1 DAC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC R2 Mux" val="TxDC DAC" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DA MONOL ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DA MONOL ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DA MONOR ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DA MONOR ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DAC2 Playback Volume" val="167" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DAC2 Playback Volume" val="175" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Stereo DAC MIXL DAC L2 Switch" val="1"/>
          <ctl name="Stereo DAC MIXR DAC R2 Switch" val="1"/>

          <ctl name="HPO MIX DAC1 Switch" val="1"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="bt-sco">
        <path name="on">
          <ctl name="RxDP Mux" val="IF1 DAC"/>
          <ctl name="RxDP SRC Switch" val="Divided by 3"/>
          <ctl name="DSP DL Mux" val="DSP"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track"/>
          <ctl name="DSP Function Switch" val="BtMic ezAEC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DSP Function Switch" val="BtMic AEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="bt-ns"/>
          <ctl name="DSP Function Switch" val="BtMic ezAEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="bt-!ns"/>
          <ctl name="DAC L2 Mux" val="TxDC DAC"/>
          <ctl name="DA MONOL ASRC Switch" val="clk_i2s1_track"/>
          <ctl name="DAC2 Playback Volume" val="175"/>
          <ctl name="Mono DAC MIXL DAC L2 Switch" val="1"/>
          <ctl name="Mono DAC MIXR DAC L2 Switch" val="1"/>
          <ctl name="Mono DAC MIXR DAC R2 Switch" val="0"/>
          <ctl name="Mono ADC L1 Mux" val="Mono DAC MIXL"/>
          <ctl name="Mono ADC R1 Mux" val="Mono DAC MIXR"/>
          <ctl name="AD MONOL ASRC Switch" val="clk_i2s3_track"/>
          <ctl name="AD MONOR ASRC Switch" val="clk_i2s3_track"/>
          <ctl name="Mono ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Mono ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="IF3 ADC Mux" val="IF_ADC2"/>
          <ctl name="BT Headphone Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="BT Headphone Switch" val="0"/>
        </path>
      </device>
      <device name="fm-tx">
        <path name="on">
          <ctl name="DAC1 L Mux" val="IF4 DAC"/>
          <ctl name="DAC1 R Mux" val="IF4 DAC"/>
          <ctl name="DA STO ASRC Switch" val="clk_sysy_div_out"/>
          <ctl name="DAC1 MIXL DAC1 Switch" val="1"/>
          <ctl name="DAC1 MIXR DAC1 Switch" val="1"/>
          <ctl name="Stereo DAC MIXL DAC L1 Switch" val="1"/>
          <ctl name="Stereo DAC MIXR DAC R1 Switch" val="1"/>
          <ctl name="Mono DAC MIXL DAC L1 Switch" val="1"/>
          <ctl name="Mono DAC MIXR DAC R1 Switch" val="1"/>
          <ctl name="FM Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="FM Switch" val="0"/>
        </path>
      </device>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="IF1 ADC Mux" val="IF1_ADC1"/>
          <ctl name="IF1 ADC1 IN2 Mux" val="IF1_ADC4"/>
          <ctl name="TxDP Capture Volume" val="108" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="TxDP Capture Volume" val="47" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="TxDP SRC Switch" val="Normal" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="TxDP SRC Switch" val="Multiplied by 3" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP Function Switch" val="BuiltinMic 48K-stereo+FFP+NS" mode="AUDIO_MODE_NORMAL" tag="rec-ns2"/>
          <ctl name="DSP Function Switch" val="BuiltinMic AEC-1mic" mode="AUDIO_MODE_IN_COMMUNICATION" tag="1mic-ns"/>
          <ctl name="DSP Function Switch" val="BuiltinMic AEC-2mic" mode="AUDIO_MODE_IN_COMMUNICATION" tag="2mic-ns"/>
          <ctl name="DSP ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP UL Mux" val="DSP"/>
          <ctl name="DSP UL Mux" val="Bypass" mode="AUDIO_MODE_NORMAL" tag="rec-ns1"/>
          <ctl name="DSP UL Mux" val="Bypass" tag="builtinmic-raw"/>
          <ctl name="DSP UL Mux" val="Bypass" tag="primic-raw"/>
          <ctl name="DSP UL Mux" val="Bypass" tag="secmic-raw"/>
          <ctl name="TDM Data Mux" val="Slot 0-1"/>
          <ctl name="DRC Switch" val="Enable"/>
          <ctl name="DRC Pre Boost" val="14" mode="AUDIO_MODE_NORMAL" tag="rec-ns1"/>
          <ctl name="DRC Pre Boost" val="11" mode="AUDIO_MODE_NORMAL" tag="rec-ns2"/>
          <ctl name="DRC Pre Boost" val="24" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DRC Limiter Th" val="63" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DRC Limiter Th" val="56" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Stereo1 ADC1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC Mux" val="ADC1L ADC2R"/>
          <ctl name="ADC 1_2" val="ADC"/>
          <ctl name="RECMIXL BST2 Switch" val="1"/>
          <ctl name="RECMIXL BST2 Switch" val="0" tag="secmic-raw"/>
          <ctl name="RECMIXL BST4 Switch" val="0"/>
          <ctl name="RECMIXL BST4 Switch" val="1" tag="secmic-raw"/>
          <ctl name="RECMIXR BST2 Switch" val="0"/>
          <ctl name="RECMIXR BST2 Switch" val="1" tag="primic-raw"/>
          <ctl name="RECMIXR BST4 Switch" val="1"/>
          <ctl name="RECMIXR BST4 Switch" val="0" tag="primic-raw"/>
          <ctl name="Int Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Int Mic Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="IF1 ADC Mux" val="IF1_ADC1"/>
          <ctl name="IF1 ADC1 IN2 Mux" val="IF1_ADC4"/>
          <ctl name="TxDP Capture Volume" val="108" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="TxDP Capture Volume" val="47" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="TxDP SRC Switch" val="Normal" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="TxDP SRC Switch" val="Multiplied by 3" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP Function Switch" val="HeadsetMic 48K-stereo+FFP+NS" mode="AUDIO_MODE_NORMAL" tag="rec-ns2"/>
          <ctl name="DSP Function Switch" val="HeadsetMic AEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="1mic-ns"/>
          <ctl name="DSP Function Switch" val="HeadsetMic AEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="2mic-ns"/>
          <ctl name="DSP ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DSP UL Mux" val="DSP"/>
          <ctl name="DSP UL Mux" val="Bypass" mode="AUDIO_MODE_NORMAL" tag="rec-ns1"/>
          <ctl name="TDM Data Mux" val="Slot 0-1"/>
          <ctl name="DRC Switch" val="Enable"/>
          <ctl name="DRC Pre Boost" val="14" mode="AUDIO_MODE_NORMAL" tag="rec-ns1"/>
          <ctl name="DRC Pre Boost" val="11" mode="AUDIO_MODE_NORMAL" tag="rec-ns2"/>
          <ctl name="DRC Pre Boost" val="16" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="DRC Limiter Th" val="63" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DRC Limiter Th" val="56" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_sysy_div_out" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_i2s1_track" mode="AUDIO_MODE_IN_COMMUNICATION"/>
          <ctl name="Stereo1 ADC1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC Mux" val="ADC1L ADC2R"/>
          <ctl name="ADC 1_2" val="ADC"/>
          <ctl name="RECMIXL BST1 Switch" val="1"/>
          <ctl name="RECMIXR BST1 Switch" val="1"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
        </path>
      </device>
      <device name="bt-sco-mic">
        <path name="on">
          <ctl name="IF1 ADC Mux" val="IF1_ADC1"/>
          <ctl name="IF1 ADC1 IN2 Mux" val="IF1_ADC4"/>
          <ctl name="TxDP Capture Volume" val="47"/>
          <ctl name="TxDP SRC Switch" val="Multiplied by 3"/>
          <ctl name="DSP Function Switch" val="BtMic ezAEC" mode="AUDIO_MODE_NORMAL"/>
          <ctl name="DSP Function Switch" val="BtMic AEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="bt-ns"/>
          <ctl name="DSP Function Switch" val="BtMic ezAEC" mode="AUDIO_MODE_IN_COMMUNICATION" tag="bt-!ns"/>
          <ctl name="DSP ASRC Switch" val="clk_i2s1_track"/>
          <ctl name="DSP UL Mux" val="DSP"/>
          <ctl name="TDM Data Mux" val="Slot 0-1"/>
          <ctl name="DRC Switch" val="Enable"/>
          <ctl name="DRC Pre Boost" val="16"/>
          <ctl name="DRC Limiter Th" val="48"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_i2s1_track"/>
          <ctl name="Stereo1 ADC1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC Mux" val="ADC1L ADC2R"/>
          <ctl name="ADC 1_2" val="Stereo DAC"/>
          <ctl name="Stereo DAC MIXL DAC L1 Switch" val="1"/>
          <ctl name="Stereo DAC MIXL DAC L2 Switch" val="0"/>
          <ctl name="Stereo DAC MIXR DAC R1 Switch" val="1"/>
          <ctl name="Stereo DAC MIXR DAC R2 Switch" val="0"/>
          <ctl name="Mono DAC MIXL DAC L1 Switch" val="0"/>
          <ctl name="Mono DAC MIXR DAC R1 Switch" val="0"/>
          <ctl name="DAC1 MIXL DAC1 Switch" val="1"/>
          <ctl name="DAC1 MIXR DAC1 Switch" val="1"/>
          <ctl name="DA STO ASRC Switch" val="clk_i2s3_track"/>
          <ctl name="DAC1 L Mux" val="IF3 DAC"/>
          <ctl name="DAC1 R Mux" val="IF3 DAC"/>
          <ctl name="DAC IF3 Data Switch" val="left copy to right"/>
          <ctl name="BT Mic Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="BT Mic Switch" val="0"/>
        </path>
      </device>
      <device name="fm-rx">
        <path name="on">
          <ctl name="IF1 ADC Mux" val="IF1_ADC1"/>
          <ctl name="IF1 ADC1 IN2 Mux" val="IF1_ADC1_IN1"/>
          <ctl name="IF1 ADC1 IN1 Mux" val="IF_ADC1"/>
          <ctl name="DRC Switch" val="Disable"/>
          <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1"/>
          <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1"/>
          <ctl name="AD STO1 ASRC Switch" val="clk_sysy_div_out"/>
          <ctl name="Stereo1 ADC1 Mux" val="ADC"/>
          <ctl name="Stereo1 ADC Mux" val="ADC1L ADC2R"/>
          <ctl name="ADC 1_2" val="Stereo DAC"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

<alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
</alsa_device>
</AudioConfigs>
